### ISSUE TITLE
convert no longer works on example.scad

### ISSUE THREAD

**Issue by dlarue** [bmsleight/lasercut#14]
I ran the following from inside the cloned repo:

export OPENSCAD_BIN=/usr/bin/openscad-nightly 
bash ./convert-2d.sh examples.scad

The resulting examples.scad_2d.scad file is filled with lots of warning messages like this one so there is no usable generated output:

WARNING: variable screw_tab_holes_a not specified as parameter, in file lasercut.scad, line 639
WARNING: variable twist_holes_a not specified as parameter, in file lasercut.scad, line 639
WARNING: variable clip_holes_a not specified as parameter, in file lasercut.scad, line 639
WARNING: len() parameter could not be converted, in file lasercut.scad, line 90
WARNING: len() parameter could not be converted, in file lasercut.scad, line 94
WARNING: len() parameter could not be converted, in file lasercut.scad, line 116
WARNING: len() parameter could not be converted, in file lasercut.scad, line 120
WARNING: len() parameter could not be converted, in file lasercut.scad, line 132
WARNING: len() parameter could not be converted, in file lasercut.scad, line 152
WARNING: len() parameter could not be converted, in file lasercut.scad, line 156
WARNING: len() parameter could not be converted, in file lasercut.scad, line 164

**Comment by bmsleight** [comment]
Eek - that does not look good. I will have a look

**Comment by bmsleight** [comment]
It works for me, 

```
export OPENSCAD_BIN=/usr/bin/openscad
bash ./convert-2d.sh examples.scad

``` 

Gives no errors. But I am using an old openscad verison

```
$ openscad --version
OpenSCAD version 2015.03-1 

```
Installed nightly 

```
$ export OPENSCAD_BIN=/snap/bin/openscad-nightly
$ /bin/bash ./convert-2d.sh examples.scad 

$ /snap/bin/openscad-nightly 2d_examples.scad -o 2d_examples.scad.dxf 
ECHO: "[LC] // screw thread major dia must be < 3.1"
ECHO: "[LC] // screw thread length must be < 15.5"
ECHO: "[LC] // nut thickness must be < 3.1"
ECHO: "[LC] // nut flats must be < 9.3"
ECHO: "[LC] // screw thread major dia must be < 3.1"
ECHO: "[LC] // screw thread length must be < 15.5"
ECHO: "[LC] // nut thickness must be < 3.1"
ECHO: "[LC] // nut flats must be < 9.3"
$

```


Any more details as I can not replicate ?

**Comment by dlarue** [comment]
I added post processing to the convert script to removed the WARNING comments and it works.
sed -i -n '/WARNING/!p' $TMPSCAD

I was testing another tool called laserscad and it too was failing with openscad-nightly but after downloading v2015-03-2 from the Ubuntu repo laserscad works and lasercut almost works.
I'm only getting these warnings now:

WARNING: Ignoring unknown variable 'screw_tab_holes_a'.
WARNING: Ignoring unknown variable 'twist_holes_a'.
WARNING: Ignoring unknown variable 'clip_holes_a'.

**Comment by dlarue** [comment]
Spoke too soon.  

dlarue@Lenovo:~/Kinetic_Clock/CAD/lasercut$ openscad-nightly --version
OpenSCAD version 2019.05.10.nightly


I went and deleted all existing files for the examples.scad which were generated previously and ran with "export OPENSCAD_BIN=/usr/bin/openscad-nightly" then
bash ./convert-2d.sh examples.scad 

saw this console output:
dlarue@Lenovo:~/Kinetic_Clock/CAD/lasercut$ bash ./convert-2d.sh examples.scad 
ECHO: "[LC] // screw thread major dia must be < 3.1"
ECHO: "[LC] // screw thread length must be < 15.5"
ECHO: "[LC] // nut thickness must be < 3.1"
ECHO: "[LC] // nut flats must be < 9.3"
ECHO: "[LC] // screw thread major dia must be < 3.1"
ECHO: "[LC] // screw thread length must be < 15.5"
ECHO: "[LC] // nut thickness must be < 3.1"
ECHO: "[LC] // nut flats must be < 9.3"

but got this scad file:
// May need to adjust location of <lasercut.scad> 
use <lasercut.scad>	;
$fn=60;
projection(cut = false)

// screw thread major dia must be < 3.1
// screw thread length must be < 15.5
// nut thickness must be < 3.1
// nut flats must be < 9.3
lasercutout(thickness = 3.1, 
          points = [[0, 0], [100, 0], [100, 75], [0, 75], [0, 0]]
        , simple_tab_holes = [[360, 23.45, 37.5], [360, 73.45, 37.5]]
        , captive_nuts = [[0, 50, 75, 7]]
        , twist_holes = [[270, 50, 18.75, 37.5]]
        ) 

lasercutout(thickness = 3.1, 
          points = [[0, 0], [100, 0], [100, 75], [0, 75], [0, 0]]
        , simple_tab_holes = [[360, 23.45, 37.5], [360, 73.45, 37.5]]
        , twist_holes = [[270, 50, 18.75, 37.5]]
        , clips = [[0, 50, 75]]
        ) 

lasercutout(thickness = 3.1, 
          points = [[0, 0], [100, 0], [100, 181.4], [0, 181.4], [0, 0]]
        , simple_tabs = [[0, 75, 181.4], [0, 25, 181.4], [180, 75, 0], [180, 25, 0]]
        ) 

lasercutout(thickness = 3.1, 
          points = [[0, 0], [37.5, 0], [37.5, 200], [0, 200], [0, 0]]
        , twist_connect = [[270, 18.75, 6.2], [270, 18.75, 190.7]]
        ) 

WARNING: variable screw_tab_holes_a not specified as parameter, in file lasercut.scad, line 639
WARNING: variable twist_holes_a not specified as parameter, in file lasercut.scad, line 639
WARNING: variable clip_holes_a not specified as parameter, in file lasercut.scad, line 639
WARNING: len() parameter could not be converted, in file lasercut.scad, line 90
WARNING: len() parameter could not be converted, in file lasercut.scad, line 94
WARNING: len() parameter could not be converted, in file lasercut.scad, line 116
WARNING: len() parameter could not be converted, in file lasercut.scad, line 120
WARNING: len() parameter could not be converted, in file lasercut.scad, line 132
WARNING: len() parameter could not be converted, in file lasercut.scad, line 152
WARNING: len() parameter could not be converted, in file lasercut.scad, line 156
WARNING: len() parameter could not be converted, in file lasercut.scad, line 164
lasercutout(thickness = 3.1, 
          points = [[0, 0], [93.8, 0], [93.8, 193.8], [0, 193.8], [0, 0]]
        , simple_tabs = [[180, -1.55, 0], [180, -1.55, 196.9], [270, 93.8, -1.55]]
        , captive_nut_holes = [[180, 50, 0]]
        , finger_joints = [[0, 1, 2], [180, 1, 2], [90, 1, 2], [270, 0, 2]]
        , clip_holes = [[0, 50, 190.7]]
        ) 

WARNING: len() parameter could not be converted, in file lasercut.scad, line 90
WARNING: len() parameter could not be converted, in file lasercut.scad, line 94
WARNING: len() parameter could not be converted, in file lasercut.scad, line 116
WARNING: len() parameter could not be converted, in file lasercut.scad, line 120
WARNING: len() parameter could not be converted, in file lasercut.scad, line 128
WARNING: len() parameter could not be converted, in file lasercut.scad, line 132
WARNING: len() parameter could not be converted, in file lasercut.scad, line 144
WARNING: len() parameter could not be converted, in file lasercut.scad, line 152
WARNING: len() parameter could not be converted, in file lasercut.scad, line 156
WARNING: len() parameter could not be converted, in file lasercut.scad, line 164
lasercutout(thickness = 3.1, 
          points = [[0, 0], [93.8, 0], [93.8, 193.8], [0, 193.8], [0, 0]]
        , simple_tabs = [[180, -1.55, 0], [270, 93.8, -1.55]]
        , finger_joints = [[0, 0, 2], [180, 1, 2], [90, 1, 2], [270, 0, 2]]
        , circles_remove = [[25, 46.9, 100]]
        ) 

WARNING: len() parameter could not be converted, in file lasercut.scad, line 90
WARNING: len() parameter could not be converted, in file lasercut.scad, line 94
WARNING: len() parameter could not be converted, in file lasercut.scad, line 116
WARNING: len() parameter could not be converted, in file lasercut.scad, line 120
WARNING: len() parameter could not be converted, in file lasercut.scad, line 128
WARNING: len() parameter could not be converted, in file lasercut.scad, line 132
WARNING: len() parameter could not be converted, in file lasercut.scad, line 144
WARNING: len() parameter could not be converted, in file lasercut.scad, line 148
WARNING: len() parameter could not be converted, in file lasercut.scad, line 152
WARNING: len() parameter could not be converted, in file lasercut.scad, line 156
WARNING: len() parameter could not be converted, in file lasercut.scad, line 164
lasercutout(thickness = 3.1, 
          points = [[0, 0], [93.8, 0], [93.8, 43.8], [0, 43.8], [0, 0]]
        , finger_joints = [[0, 1, 2], [180, 0, 2], [90, 1, 2], [270, 0, 2]]
        ) 

WARNING: len() parameter could not be converted, in file lasercut.scad, line 90
WARNING: len() parameter could not be converted, in file lasercut.scad, line 94
WARNING: len() parameter could not be converted, in file lasercut.scad, line 116
WARNING: len() parameter could not be converted, in file lasercut.scad, line 120
WARNING: len() parameter could not be converted, in file lasercut.scad, line 128
WARNING: len() parameter could not be converted, in file lasercut.scad, line 132
WARNING: len() parameter could not be converted, in file lasercut.scad, line 144
WARNING: len() parameter could not be converted, in file lasercut.scad, line 148
WARNING: len() parameter could not be converted, in file lasercut.scad, line 152
WARNING: len() parameter could not be converted, in file lasercut.scad, line 156
WARNING: len() parameter could not be converted, in file lasercut.scad, line 164
lasercutout(thickness = 3.1, 
          points = [[0, 0], [93.8, 0], [93.8, 43.8], [0, 43.8], [0, 0]]
        , simple_tabs = [[0, -1.55, 43.8], [180, 95.35, 0]]
        , finger_joints = [[0, 1, 2], [180, 1, 2], [90, 1, 2], [270, 0, 2]]
        ) 

WARNING: len() parameter could not be converted, in file lasercut.scad, line 90
WARNING: len() parameter could not be converted, in file lasercut.scad, line 94
WARNING: len() parameter could not be converted, in file lasercut.scad, line 116
WARNING: len() parameter could not be converted, in file lasercut.scad, line 120
WARNING: len() parameter could not be converted, in file lasercut.scad, line 128
WARNING: len() parameter could not be converted, in file lasercut.scad, line 132
WARNING: len() parameter could not be converted, in file lasercut.scad, line 144
WARNING: len() parameter could not be converted, in file lasercut.scad, line 148
WARNING: len() parameter could not be converted, in file lasercut.scad, line 152
WARNING: len() parameter could not be converted, in file lasercut.scad, line 156
WARNING: len() parameter could not be converted, in file lasercut.scad, line 164
lasercutout(thickness = 3.1, 
          points = [[0, 0], [43.8, 0], [43.8, 193.8], [0, 193.8], [0, 0]]
        , finger_joints = [[0, 0, 2], [180, 1, 2], [90, 0, 2], [270, 1, 2]]
        ) 

WARNING: len() parameter could not be converted, in file lasercut.scad, line 90
WARNING: len() parameter could not be converted, in file lasercut.scad, line 94
WARNING: len() parameter could not be converted, in file lasercut.scad, line 116
WARNING: len() parameter could not be converted, in file lasercut.scad, line 120
WARNING: len() parameter could not be converted, in file lasercut.scad, line 128
WARNING: len() parameter could not be converted, in file lasercut.scad, line 132
WARNING: len() parameter could not be converted, in file lasercut.scad, line 144
WARNING: len() parameter could not be converted, in file lasercut.scad, line 148
WARNING: len() parameter could not be converted, in file lasercut.scad, line 152
WARNING: len() parameter could not be converted, in file lasercut.scad, line 156
WARNING: len() parameter could not be converted, in file lasercut.scad, line 164
lasercutout(thickness = 3.1, 
          points = [[0, 0], [43.8, 0], [43.8, 193.8], [0, 193.8], [0, 0]]
        , simple_tabs = [[0, 45.35, 193.8]]
        , finger_joints = [[0, 0, 2], [180, 1, 2], [90, 0, 2], [270, 1, 2]]
        ) 

;

**Comment by bmsleight** [comment]
Ok I'm on a different version.

$ /snap/bin/openscad-nightly --version
OpenSCAD version 2019.03.31

May be related: https://github.com/openscad/openscad/issues/1584
http://forum.openscad.org/A-warning-too-far-td25451.html

**Comment by dlarue** [comment]
Yes, that does look related.
I noticed the captiveNut is new and one of the first len() errors.  I love the feature and have been looking for it ever since using it on the FabScan.  BTW, at minute 6:25 you can see how these guys changed it from square to angled. https://www.youtube.com/watch?v=3Q2Xv1Y1mdU
I found it easy to use.

**Comment by bmsleight** [comment]
Thanks for the bug report.
