### ISSUE TITLE
Full-2D library

### ISSUE THREAD

**Issue by Salamandar** [bmsleight/lasercut#17]
Your library is full-3D. That means that :
* Performance is down
* You need to do tricks like `translate([0, 0, -thickness]) cube([5, 5, thickness*3]);`

With 2D code, you can do : `square([5, 5]);`. There will be no issues due to faces being at the same place and all.
It also enforces the result as 2D objects.

I'm currently working on it.

Also, you need to pass `thickness` to every module in the code. In 2D, you only need a `linear_extrude` **once in the whole file**.
That also allows users to stay in 2D, do the linear_extrude themselves if they want. 

EDIT : yeah, you still need to pass `thickness` to every module. Still, the performance impact is very noticeable.

**Comment by Salamandar** [comment]
Oddly enough, the performance impact is **very** noticeable when moving the camera in preview mode. It goes from very laggy to almost-60fps.

**Comment by bmsleight** [comment]
HI Salamandar,

The Library is full 3d, bu design. I like to see the final boxes in lien with my other 3d models, the bonus is that I can confirm to 2d cad files with ease. (Although I still do not have a laser cutter.

With respect, I am closing as will not fix. PR or forks are still welcome.

Regards,
Brendan
