### ISSUE TITLE
Compatibility of convert-2d.sh on Mac OSX

### ISSUE THREAD

**Issue by Vincent14** [bmsleight/lasercut#2]
I've called the script on the lastest Mac OSX El Capitan.

I've changed the script and used the complete path to openscad (/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD).

Now, if I call the script I get this error:
`sed: 1: "$a;": command a expects \ followed by text`

Someone on stackoverflow says sed is an old version on Mac, more strict.

**Comment by Vincent14** [comment]
I've totally rewritten the script for Mac & Linux compatibility:
```
# Defines where OpenSCAD is installed

openscad_bin() {
  if [[ "$OSTYPE" == "darwin"* ]]; then
    /Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD $1
  else
    openscad $1
  fi
}


# Creates a 2d plan of your 3D model

openscad_bin "$1 -D generate=1 -o /tmp/$1.csg" 2>&1 >/dev/null | sed -e 's/ECHO: \"\[LC\] //' -e 's/"$//' -e '$a\
;' >./2d_$1

sed -i.tmp '1 i\
use <lasercut.scad>;\
\$fn=60;\
projection(cut = false)\
' ./2d_$1

rm 2d_$1.tmp

# Exports in others formats (could be very long)

#openscad_bin "./2d_$1 -o ./2d_$1.csg"
#openscad_bin "./2d_$1 -o ./2d_$1.dxf"
#openscad_bin "./2d_$1 -o ./2d_$1.svg"
#openscad_bin "./$1 -o ./3d_$1.stl"
```

**Comment by Vincent14** [comment]
Could you integrate it on github?

**Comment by bmsleight** [comment]
Sorry on leave.
But Thanks for the patch, will look at it soonest.

**Comment by rogerclarkmelbourne** [comment]
@Vincent14 

I forked the repo as I found some other problems, so I've updated convert-2d.sh in my fork

https://github.com/rogerclarkmelbourne/lasercut/commits/master

Note. My fork has some other changes as well, to fix the issue with thickness not being applied to lasercutbox() and also adds kerf width to finger joints, and fixes an issue where the last finger joint tab can be missing

**Comment by bmsleight** [comment]
Thanks @Vincent14  I see that @rogerclarkmelbourne merged this into his fork, so when merging his fork back this is now resolved.
Sorry for the loooooong delay.

**Comment by Vincent14** [comment]
I always use your library so that's definitely a GOOD news!
