### ISSUE TITLE
holes at corners of 3-way finger joints

### ISSUE THREAD

**Issue by jreiberkyle** [bmsleight/lasercut#33]
At 3-way finger joints, I am unable to find a way to not have a hole at the corner of the joint, like this:

![image](https://user-images.githubusercontent.com/2984664/197822736-f616db60-3875-4dda-bbf9-b94cfc3e03d8.png)

Entire model, exploded view:
![image](https://user-images.githubusercontent.com/2984664/197823242-3fd678f4-5e68-4adc-ba0c-f44101f1f3bb.png)

Script:
```openscad
include <lasercut.scad>;

thickness = 3;

// inside dimensions
lasercut_x = 50;
lasercut_y = 100;
lasercut_z = 20;
lasercut_thickness = thickness; // allows for kerf adjustments, etc

spacing = 0; // spacing between parts for visualization


outside_y = lasercut_y + thickness;

bottom();
translate([0, -spacing, 0]) side(); translate([0, outside_y + spacing, 0]) side();
translate([spacing, 0, 0]) front();

module front()
{
translate([lasercut_x,0,thickness + lasercut_z]) 
    rotate([0,90,0]) 
  lasercutoutSquare(thickness=lasercut_thickness, x=lasercut_z, y=lasercut_y,
        finger_joints=[[UP, 0, 2], [DOWN, 1, 2], [RIGHT, 0, 4]]
 );
}

module bottom()
{
lasercutoutSquare(thickness=lasercut_thickness, x=lasercut_x, y=lasercut_y,
        finger_joints=[[UP, 1, 4], [DOWN, 0, 4], [RIGHT, 1, 4]]
 );
}


module side()
{
translate([0,0,thickness]) rotate([90,0,0]) 
    lasercutoutSquare(thickness=thickness, x=lasercut_x, y=lasercut_z,
        finger_joints=[[DOWN, 1, 4], [RIGHT, 1, 2]]
    );
}

```

**Comment by bmsleight** [comment]
Away from computer until the week end.

The lasercutoutBox function may help. You could do it as a lasercutoutBox
as sides=5


include <lasercut.scad>;

thickness = 3.1;
x = 50;
y = 50;
z = 75;


for (sides =[4:6])
{
    color("Gold",0.75) translate([100*(sides-4),0,0])
        lasercutoutBox(thickness = thickness, x=x, y=y, z=z,
        sides=sides, num_fingers=4);
}

**Comment by bmsleight** [comment]
Sorry just trying to read on mobile
Does making start_up=1 on the right-hand side piece help ?

**Comment by bmsleight** [comment]
This was a fun one. 
I have opened #34 as a feature request. 

The lasercutoutBox() using add addition simple_tabs to fill in the corners. (Took me a while to remember this in my code)  https://github.com/bmsleight/lasercut/blob/master/lasercut.scad#L627

So to fill in the corners on the above example 
        simple_tabs=[[DOWN, lasercut_x+thickness*0.5, 0]]

Full example:-

```
include <lasercut.scad>;

thickness = 3;

// inside dimensions
lasercut_x = 50;
lasercut_y = 100;
lasercut_z = 20;
lasercut_thickness = thickness; // allows for kerf adjustments, etc

spacing = 0; // spacing between parts for visualization


outside_y = lasercut_y + thickness;

bottom();
translate([0, -spacing, 0]) side(); translate([0, outside_y + spacing, 0]) side();
translate([spacing, 0, 0]) front();

module front()
{
translate([lasercut_x,0,thickness + lasercut_z]) 
    rotate([0,90,0]) 
  lasercutoutSquare(thickness=lasercut_thickness, x=lasercut_z, y=lasercut_y,
        finger_joints=[[UP, 0, 2], [DOWN, 1, 2], [RIGHT, 0, 4]]
 );
}

module bottom()
{
lasercutoutSquare(thickness=lasercut_thickness, x=lasercut_x, y=lasercut_y,
        finger_joints=[[UP, 1, 4], [DOWN, 0, 4], [RIGHT, 1, 4]]
 );
}


module side()
{
translate([0,0,thickness]) rotate([90,0,0]) 
    lasercutoutSquare(thickness=thickness, x=lasercut_x, y=lasercut_z,
        finger_joints=[[DOWN, 1, 4], [RIGHT, 1, 2]],
        simple_tabs=[[DOWN, lasercut_x+thickness*0.5, 0]]
    );
}
```

In the above example, starting from [0], it is side [5], [0],[2],[3] or lasercutBox
