### ISSUE TITLE
Kerf calculations are incorrect

### ISSUE THREAD

**Issue by AlexCPU** [bmsleight/lasercut#36]
First and last cubes in a row of fingers calculate position/size incorrectly for kerf.

<img width="978" alt="image" src="https://user-images.githubusercontent.com/4178651/205485271-4c582ced-07a0-4f1a-87dd-4643c86f129a.png">
Taking an extreme example generating fingers along a 100 edge, with kerf set at 10 highlights the issue where the first and last gaps and blocks are too big, last block even overhangs the edge of the shape.

```
include <lasercut.scad>; 

thickness = 3;
max_x=100;
min_x=0;
max_y=10;
min_y=0;
kerf =10;

        range_min = min_x; 
        range_max = max_x; 
        t_x = min_x;
        t_y = max_y;


 fingers(UP, 0, 5, thickness, range_min, range_max, t_x, t_y);
 translate ([0, max_y/2,0]) fingers(UP, 1, 5, thickness, range_min, range_max, t_x, t_y, bumps=false); 
 cube([max_x,8,thickness]);
 ```

**Comment by AlexCPU** [comment]
Looks like the kerf calculations are off as well, the picture shows a kerf of 5, even though the kerf is set to 10

**Comment by bmsleight** [comment]
Thanks for reporting - will look into this. I need to put some test case together to capture these kind of errors,
Hoe did you find the error ?

**Comment by AlexCPU** [comment]
I've been fiddling around as I'd like to change the fingers to be symmetrical (i.e. start_up=1 has one more tab than start_up=0), and to support a tabsize attribute (so that thin flat boxes can have one tab on the short edge, and many on the long edge).

The easiest way I've found to make sure that you've got your kerf code correct is to set it really high and watch if everything breaks (which it did).

I've got a fix that works for the above example now, just need to check it out against all the other functions that use it.

**Comment by AlexCPU** [comment]
Think I got it.  Attached PR should do it.  Also found that the bumps weren't compensated for kerf, so sometimes ended up inside the tabs.
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/4178651/205491454-ce95f9ce-5071-4cb6-9cdc-0e8e75c04775.png">

**Comment by bmsleight** [comment]
Thanks for the report and the pull.
