### ISSUE TITLE
lasercutoutBox only works when thickness is 3.1mm

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [bmsleight/lasercut#4]
There seems to be some problem passing in the thickness, so that the lasercutBox only works if the thickness is set to 3.1

I'm using OpenSCAD version 2015.03-2

**Comment by bmsleight** [comment]
Hi Roger - got an example snippet ?

**Comment by rogerclarkmelbourne** [comment]
Brendan

I just figured out why its not working.

in lasercutoutBoxAdjustedFJ() you are not passing the thickness into the calls to lasercutoutSquare()

So they default to 3.1mm thick

I can do a PR is you want.

**Comment by rogerclarkmelbourne** [comment]
I've forked your repo and applied my fix for this issue

See 

https://github.com/rogerclarkmelbourne/lasercut/commits/master

**Comment by bmsleight** [comment]
Roger sorry for the long delay (years!)
Now I have a machine to actually use, I have merge your fork back in to mine. Thanks for all the updates. 
Brendan
