### ISSUE TITLE
Finger joint corner notches

### ISSUE THREAD

**Issue by scttnlsn** [bmsleight/lasercut#8]
I'm trying to create a 5-sided finger jointed box with a removable lid and since I could not figure out how to add `captive_nuts` to the sides of a `lasercutoutBox` (is that possible?) I decided to create 5 `lasercutoutSquare`s, each with `finger_joints`.  I noticed that the corners remained notched out as seen here: ![](https://imgur.com/download/e2gbIJK)  It's possible to make finger joints such that these notches do not exist but I wasn't sure how to do it with this module.  Can I make such a design with `lasercut`?

**Comment by scttnlsn** [comment]
Here's another image with the opacity turned down a bit: ![](https://imgur.com/download/gXtXRhA)

**Comment by bmsleight** [comment]
Latest commit resolves (a fork I think caused this issue, examples now run ok again

Older commit
![broke_simple_tabs](https://user-images.githubusercontent.com/3758389/39967405-2f0d0d62-56aa-11e8-866b-fb2408cd0922.png)

Current example 5
![simple_tabs](https://user-images.githubusercontent.com/3758389/39967406-30d6e38e-56aa-11e8-833d-237cb2d41af5.png)

**Comment by dogtopus** [comment]
Pretty sure this is not resolved. The example is OK but the manually built box (with `lasercutoutSquare`) remains notched and extra tabs needs to be added to plug those notches.
A flag that automatically plug these notches would be nice to have.
